-- table classes
-- count +~ 800

-- sequence : yaboi
create sequence class_sequence
    minvalue 1
    maxvalue 9999
    start with 1
    increment by 1
    cache 20;
/
create or replace function next_class_sequence
    return varchar2
    as
    begin
        return('CL' || to_char(class_sequence.nextval, 'fm0000'));
    end;
/

-- trigger : yaboi

create or replace trigger trigger_insert_classes
    before insert on classes
    for each row
    begin
        if :new.class_id is null then
            select next_class_sequence into :new.class_id from dual;
        end if;
    end;
/

insert into classes (COURSE_ID, CLASS_NAME) values ('C0001', 'Life coaching - Class 1');
insert into classes (COURSE_ID, CLASS_NAME) values ('C0001', 'Life coaching - Class 2');
insert into classes (COURSE_ID, CLASS_NAME) values ('C0002', 'Machine Learning w/ python - Class 1');
insert into classes (COURSE_ID, CLASS_NAME) values ('C0002', 'Machine Learning w/ python - Class 2');
insert into classes (course_id, class_name) values ('C0003', 'Beginner Assembly Language - Class 1');
insert into classes (course_id, class_name) values ('C0003', 'Beginner Assembly Language - Class 2');
insert into classes (course_id, class_name) values ('C0004', 'Intermediate Assembly Language - Class 1');
insert into classes (course_id, class_name) values ('C0004', 'Intermediate Assembly Language - Class 2');
insert into classes (course_id, class_name) values ('C0005', 'Advanced Assembly Language - Class 1');
insert into classes (course_id, class_name) values ('C0005', 'Advanced Assembly Language - Class 2');
insert into classes (course_id, class_name) values ('C0006', 'Practical Assembly Language - Class 1');
insert into classes (course_id, class_name) values ('C0006', 'Practical Assembly Language - Class 2');
insert into classes (course_id, class_name) values ('C0007', 'Beginner Apex - Class 1');
insert into classes (course_id, class_name) values ('C0007', 'Beginner Apex - Class 2');
insert into classes (course_id, class_name) values ('C0008', 'Intermediate Apex - Class 1');
insert into classes (course_id, class_name) values ('C0008', 'Intermediate Apex - Class 2');
insert into classes (course_id, class_name) values ('C0009', 'Advanced Apex - Class 1');
insert into classes (course_id, class_name) values ('C0009', 'Advanced Apex - Class 2');
insert into classes (course_id, class_name) values ('C0010', 'Practical Apex - Class 1');
insert into classes (course_id, class_name) values ('C0010', 'Practical Apex - Class 2');
insert into classes (course_id, class_name) values ('C0011', 'Beginner Argus - Class 1');
insert into classes (course_id, class_name) values ('C0011', 'Beginner Argus - Class 2');
insert into classes (course_id, class_name) values ('C0012', 'Intermediate Argus - Class 1');
insert into classes (course_id, class_name) values ('C0012', 'Intermediate Argus - Class 2');
insert into classes (course_id, class_name) values ('C0013', 'Advanced Argus - Class 1');
insert into classes (course_id, class_name) values ('C0013', 'Advanced Argus - Class 2');
insert into classes (course_id, class_name) values ('C0014', 'Practical Argus - Class 1');
insert into classes (course_id, class_name) values ('C0014', 'Practical Argus - Class 2');
insert into classes (course_id, class_name) values ('C0015', 'Beginner AutoHotkey - Class 1');
insert into classes (course_id, class_name) values ('C0015', 'Beginner AutoHotkey - Class 2');
insert into classes (course_id, class_name) values ('C0016', 'Intermediate AutoHotkey - Class 1');
insert into classes (course_id, class_name) values ('C0016', 'Intermediate AutoHotkey - Class 2');
insert into classes (course_id, class_name) values ('C0017', 'Advanced AutoHotkey - Class 1');
insert into classes (course_id, class_name) values ('C0017', 'Advanced AutoHotkey - Class 2');
insert into classes (course_id, class_name) values ('C0018', 'Practical AutoHotkey - Class 1');
insert into classes (course_id, class_name) values ('C0018', 'Practical AutoHotkey - Class 2');
insert into classes (course_id, class_name) values ('C0019', 'Beginner AWK - Class 1');
insert into classes (course_id, class_name) values ('C0019', 'Beginner AWK - Class 2');
insert into classes (course_id, class_name) values ('C0020', 'Intermediate AWK - Class 1');
insert into classes (course_id, class_name) values ('C0020', 'Intermediate AWK - Class 2');
insert into classes (course_id, class_name) values ('C0021', 'Advanced AWK - Class 1');
insert into classes (course_id, class_name) values ('C0021', 'Advanced AWK - Class 2');
insert into classes (course_id, class_name) values ('C0022', 'Practical AWK - Class 1');
insert into classes (course_id, class_name) values ('C0022', 'Practical AWK - Class 2');
insert into classes (course_id, class_name) values ('C0023', 'Beginner Bash - Class 1');
insert into classes (course_id, class_name) values ('C0023', 'Beginner Bash - Class 2');
insert into classes (course_id, class_name) values ('C0024', 'Intermediate Bash - Class 1');
insert into classes (course_id, class_name) values ('C0024', 'Intermediate Bash - Class 2');
insert into classes (course_id, class_name) values ('C0025', 'Advanced Bash - Class 1');
insert into classes (course_id, class_name) values ('C0025', 'Advanced Bash - Class 2');
insert into classes (course_id, class_name) values ('C0026', 'Practical Bash - Class 1');
insert into classes (course_id, class_name) values ('C0026', 'Practical Bash - Class 2');
insert into classes (course_id, class_name) values ('C0027', 'Beginner Batch - Class 1');
insert into classes (course_id, class_name) values ('C0027', 'Beginner Batch - Class 2');
insert into classes (course_id, class_name) values ('C0028', 'Intermediate Batch - Class 1');
insert into classes (course_id, class_name) values ('C0028', 'Intermediate Batch - Class 2');
insert into classes (course_id, class_name) values ('C0029', 'Advanced Batch - Class 1');
insert into classes (course_id, class_name) values ('C0029', 'Advanced Batch - Class 2');
insert into classes (course_id, class_name) values ('C0030', 'Practical Batch - Class 1');
insert into classes (course_id, class_name) values ('C0030', 'Practical Batch - Class 2');
insert into classes (course_id, class_name) values ('C0031', 'Beginner BeanShell - Class 1');
insert into classes (course_id, class_name) values ('C0031', 'Beginner BeanShell - Class 2');
insert into classes (course_id, class_name) values ('C0032', 'Intermediate BeanShell - Class 1');
insert into classes (course_id, class_name) values ('C0032', 'Intermediate BeanShell - Class 2');
insert into classes (course_id, class_name) values ('C0033', 'Advanced BeanShell - Class 1');
insert into classes (course_id, class_name) values ('C0033', 'Advanced BeanShell - Class 2');
insert into classes (course_id, class_name) values ('C0034', 'Practical BeanShell - Class 1');
insert into classes (course_id, class_name) values ('C0034', 'Practical BeanShell - Class 2');
insert into classes (course_id, class_name) values ('C0035', 'Beginner C - Class 1');
insert into classes (course_id, class_name) values ('C0035', 'Beginner C - Class 2');
insert into classes (course_id, class_name) values ('C0036', 'Intermediate C - Class 1');
insert into classes (course_id, class_name) values ('C0036', 'Intermediate C - Class 2');
insert into classes (course_id, class_name) values ('C0037', 'Advanced C - Class 1');
insert into classes (course_id, class_name) values ('C0037', 'Advanced C - Class 2');
insert into classes (course_id, class_name) values ('C0038', 'Practical C - Class 1');
insert into classes (course_id, class_name) values ('C0038', 'Practical C - Class 2');
insert into classes (course_id, class_name) values ('C0039', 'Beginner C-- - Class 1');
insert into classes (course_id, class_name) values ('C0039', 'Beginner C-- - Class 2');
insert into classes (course_id, class_name) values ('C0040', 'Intermediate C-- - Class 1');
insert into classes (course_id, class_name) values ('C0040', 'Intermediate C-- - Class 2');
insert into classes (course_id, class_name) values ('C0041', 'Advanced C-- - Class 1');
insert into classes (course_id, class_name) values ('C0041', 'Advanced C-- - Class 2');
insert into classes (course_id, class_name) values ('C0042', 'Practical C-- - Class 1');
insert into classes (course_id, class_name) values ('C0042', 'Practical C-- - Class 2');
insert into classes (course_id, class_name) values ('C0043', 'Beginner C++ - Class 1');
insert into classes (course_id, class_name) values ('C0043', 'Beginner C++ - Class 2');
insert into classes (course_id, class_name) values ('C0044', 'Intermediate C++ - Class 1');
insert into classes (course_id, class_name) values ('C0044', 'Intermediate C++ - Class 2');
insert into classes (course_id, class_name) values ('C0045', 'Advanced C++ - Class 1');
insert into classes (course_id, class_name) values ('C0045', 'Advanced C++ - Class 2');
insert into classes (course_id, class_name) values ('C0046', 'Practical C++ - Class 1');
insert into classes (course_id, class_name) values ('C0046', 'Practical C++ - Class 2');
insert into classes (course_id, class_name) values ('C0047', 'Beginner C# - Class 1');
insert into classes (course_id, class_name) values ('C0047', 'Beginner C# - Class 2');
insert into classes (course_id, class_name) values ('C0048', 'Intermediate C# - Class 1');
insert into classes (course_id, class_name) values ('C0048', 'Intermediate C# - Class 2');
insert into classes (course_id, class_name) values ('C0049', 'Advanced C# - Class 1');
insert into classes (course_id, class_name) values ('C0049', 'Advanced C# - Class 2');
insert into classes (course_id, class_name) values ('C0050', 'Practical C# - Class 1');
insert into classes (course_id, class_name) values ('C0050', 'Practical C# - Class 2');
insert into classes (course_id, class_name) values ('C0051', 'Beginner CDuce - Class 1');
insert into classes (course_id, class_name) values ('C0051', 'Beginner CDuce - Class 2');
insert into classes (course_id, class_name) values ('C0052', 'Intermediate CDuce - Class 1');
insert into classes (course_id, class_name) values ('C0052', 'Intermediate CDuce - Class 2');
insert into classes (course_id, class_name) values ('C0053', 'Advanced CDuce - Class 1');
insert into classes (course_id, class_name) values ('C0053', 'Advanced CDuce - Class 2');
insert into classes (course_id, class_name) values ('C0054', 'Practical CDuce - Class 1');
insert into classes (course_id, class_name) values ('C0054', 'Practical CDuce - Class 2');
insert into classes (course_id, class_name) values ('C0055', 'Beginner Charm - Class 1');
insert into classes (course_id, class_name) values ('C0055', 'Beginner Charm - Class 2');
insert into classes (course_id, class_name) values ('C0056', 'Intermediate Charm - Class 1');
insert into classes (course_id, class_name) values ('C0056', 'Intermediate Charm - Class 2');
insert into classes (course_id, class_name) values ('C0057', 'Advanced Charm - Class 1');
insert into classes (course_id, class_name) values ('C0057', 'Advanced Charm - Class 2');
insert into classes (course_id, class_name) values ('C0058', 'Practical Charm - Class 1');
insert into classes (course_id, class_name) values ('C0058', 'Practical Charm - Class 2');
insert into classes (course_id, class_name) values ('C0059', 'Beginner COBOL - Class 1');
insert into classes (course_id, class_name) values ('C0059', 'Beginner COBOL - Class 2');
insert into classes (course_id, class_name) values ('C0060', 'Intermediate COBOL - Class 1');
insert into classes (course_id, class_name) values ('C0060', 'Intermediate COBOL - Class 2');
insert into classes (course_id, class_name) values ('C0061', 'Advanced COBOL - Class 1');
insert into classes (course_id, class_name) values ('C0061', 'Advanced COBOL - Class 2');
insert into classes (course_id, class_name) values ('C0062', 'Practical COBOL - Class 1');
insert into classes (course_id, class_name) values ('C0062', 'Practical COBOL - Class 2');
insert into classes (course_id, class_name) values ('C0063', 'Beginner CSS - Class 1');
insert into classes (course_id, class_name) values ('C0063', 'Beginner CSS - Class 2');
insert into classes (course_id, class_name) values ('C0064', 'Intermediate CSS - Class 1');
insert into classes (course_id, class_name) values ('C0064', 'Intermediate CSS - Class 2');
insert into classes (course_id, class_name) values ('C0065', 'Advanced CSS - Class 1');
insert into classes (course_id, class_name) values ('C0065', 'Advanced CSS - Class 2');
insert into classes (course_id, class_name) values ('C0066', 'Practical CSS - Class 1');
insert into classes (course_id, class_name) values ('C0066', 'Practical CSS - Class 2');
insert into classes (course_id, class_name) values ('C0067', 'Beginner Curl - Class 1');
insert into classes (course_id, class_name) values ('C0067', 'Beginner Curl - Class 2');
insert into classes (course_id, class_name) values ('C0068', 'Intermediate Curl - Class 1');
insert into classes (course_id, class_name) values ('C0068', 'Intermediate Curl - Class 2');
insert into classes (course_id, class_name) values ('C0069', 'Advanced Curl - Class 1');
insert into classes (course_id, class_name) values ('C0069', 'Advanced Curl - Class 2');
insert into classes (course_id, class_name) values ('C0070', 'Practical Curl - Class 1');
insert into classes (course_id, class_name) values ('C0070', 'Practical Curl - Class 2');
insert into classes (course_id, class_name) values ('C0071', 'Beginner Cython - Class 1');
insert into classes (course_id, class_name) values ('C0071', 'Beginner Cython - Class 2');
insert into classes (course_id, class_name) values ('C0072', 'Intermediate Cython - Class 1');
insert into classes (course_id, class_name) values ('C0072', 'Intermediate Cython - Class 2');
insert into classes (course_id, class_name) values ('C0073', 'Advanced Cython - Class 1');
insert into classes (course_id, class_name) values ('C0073', 'Advanced Cython - Class 2');
insert into classes (course_id, class_name) values ('C0074', 'Practical Cython - Class 1');
insert into classes (course_id, class_name) values ('C0074', 'Practical Cython - Class 2');
insert into classes (course_id, class_name) values ('C0075', 'Beginner DataFlex - Class 1');
insert into classes (course_id, class_name) values ('C0075', 'Beginner DataFlex - Class 2');
insert into classes (course_id, class_name) values ('C0076', 'Intermediate DataFlex - Class 1');
insert into classes (course_id, class_name) values ('C0076', 'Intermediate DataFlex - Class 2');
insert into classes (course_id, class_name) values ('C0077', 'Advanced DataFlex - Class 1');
insert into classes (course_id, class_name) values ('C0077', 'Advanced DataFlex - Class 2');
insert into classes (course_id, class_name) values ('C0078', 'Practical DataFlex - Class 1');
insert into classes (course_id, class_name) values ('C0078', 'Practical DataFlex - Class 2');
insert into classes (course_id, class_name) values ('C0079', 'Beginner Datalog - Class 1');
insert into classes (course_id, class_name) values ('C0079', 'Beginner Datalog - Class 2');
insert into classes (course_id, class_name) values ('C0080', 'Intermediate Datalog - Class 1');
insert into classes (course_id, class_name) values ('C0080', 'Intermediate Datalog - Class 2');
insert into classes (course_id, class_name) values ('C0081', 'Advanced Datalog - Class 1');
insert into classes (course_id, class_name) values ('C0081', 'Advanced Datalog - Class 2');
insert into classes (course_id, class_name) values ('C0082', 'Practical Datalog - Class 1');
insert into classes (course_id, class_name) values ('C0082', 'Practical Datalog - Class 2');
insert into classes (course_id, class_name) values ('C0083', 'Beginner dBase - Class 1');
insert into classes (course_id, class_name) values ('C0083', 'Beginner dBase - Class 2');
insert into classes (course_id, class_name) values ('C0084', 'Intermediate dBase - Class 1');
insert into classes (course_id, class_name) values ('C0084', 'Intermediate dBase - Class 2');
insert into classes (course_id, class_name) values ('C0085', 'Advanced dBase - Class 1');
insert into classes (course_id, class_name) values ('C0085', 'Advanced dBase - Class 2');
insert into classes (course_id, class_name) values ('C0086', 'Practical dBase - Class 1');
insert into classes (course_id, class_name) values ('C0086', 'Practical dBase - Class 2');
insert into classes (course_id, class_name) values ('C0087', 'Beginner DAX - Class 1');
insert into classes (course_id, class_name) values ('C0087', 'Beginner DAX - Class 2');
insert into classes (course_id, class_name) values ('C0088', 'Intermediate DAX - Class 1');
insert into classes (course_id, class_name) values ('C0088', 'Intermediate DAX - Class 2');
insert into classes (course_id, class_name) values ('C0089', 'Advanced DAX - Class 1');
insert into classes (course_id, class_name) values ('C0089', 'Advanced DAX - Class 2');
insert into classes (course_id, class_name) values ('C0090', 'Practical DAX - Class 1');
insert into classes (course_id, class_name) values ('C0090', 'Practical DAX - Class 2');
insert into classes (course_id, class_name) values ('C0091', 'Beginner ECMACScript - Class 1');
insert into classes (course_id, class_name) values ('C0091', 'Beginner ECMACScript - Class 2');
insert into classes (course_id, class_name) values ('C0092', 'Intermediate ECMACScript - Class 1');
insert into classes (course_id, class_name) values ('C0092', 'Intermediate ECMACScript - Class 2');
insert into classes (course_id, class_name) values ('C0093', 'Advanced ECMACScript - Class 1');
insert into classes (course_id, class_name) values ('C0093', 'Advanced ECMACScript - Class 2');
insert into classes (course_id, class_name) values ('C0094', 'Practical ECMACScript - Class 1');
insert into classes (course_id, class_name) values ('C0094', 'Practical ECMACScript - Class 2');
insert into classes (course_id, class_name) values ('C0095', 'Beginner Emerald - Class 1');
insert into classes (course_id, class_name) values ('C0095', 'Beginner Emerald - Class 2');
insert into classes (course_id, class_name) values ('C0096', 'Intermediate Emerald - Class 1');
insert into classes (course_id, class_name) values ('C0096', 'Intermediate Emerald - Class 2');
insert into classes (course_id, class_name) values ('C0097', 'Advanced Emerald - Class 1');
insert into classes (course_id, class_name) values ('C0097', 'Advanced Emerald - Class 2');
insert into classes (course_id, class_name) values ('C0098', 'Practical Emerald - Class 1');
insert into classes (course_id, class_name) values ('C0098', 'Practical Emerald - Class 2');
insert into classes (course_id, class_name) values ('C0099', 'Beginner EXEC CMS - Class 1');
insert into classes (course_id, class_name) values ('C0099', 'Beginner EXEC CMS - Class 2');
insert into classes (course_id, class_name) values ('C0100', 'Intermediate EXEC CMS - Class 1');
insert into classes (course_id, class_name) values ('C0100', 'Intermediate EXEC CMS - Class 2');
insert into classes (course_id, class_name) values ('C0101', 'Advanced EXEC CMS - Class 1');
insert into classes (course_id, class_name) values ('C0101', 'Advanced EXEC CMS - Class 2');
insert into classes (course_id, class_name) values ('C0102', 'Practical EXEC CMS - Class 1');
insert into classes (course_id, class_name) values ('C0102', 'Practical EXEC CMS - Class 2');
insert into classes (course_id, class_name) values ('C0103', 'Beginner EXEC 2 - Class 1');
insert into classes (course_id, class_name) values ('C0103', 'Beginner EXEC 2 - Class 2');
insert into classes (course_id, class_name) values ('C0104', 'Intermediate EXEC 2 - Class 1');
insert into classes (course_id, class_name) values ('C0104', 'Intermediate EXEC 2 - Class 2');
insert into classes (course_id, class_name) values ('C0105', 'Advanced EXEC 2 - Class 1');
insert into classes (course_id, class_name) values ('C0105', 'Advanced EXEC 2 - Class 2');
insert into classes (course_id, class_name) values ('C0106', 'Practical EXEC 2 - Class 1');
insert into classes (course_id, class_name) values ('C0106', 'Practical EXEC 2 - Class 2');
insert into classes (course_id, class_name) values ('C0107', 'Beginner Ezhill - Class 1');
insert into classes (course_id, class_name) values ('C0107', 'Beginner Ezhill - Class 2');
insert into classes (course_id, class_name) values ('C0108', 'Intermediate Ezhill - Class 1');
insert into classes (course_id, class_name) values ('C0108', 'Intermediate Ezhill - Class 2');
insert into classes (course_id, class_name) values ('C0109', 'Advanced Ezhill - Class 1');
insert into classes (course_id, class_name) values ('C0109', 'Advanced Ezhill - Class 2');
insert into classes (course_id, class_name) values ('C0110', 'Practical Ezhill - Class 1');
insert into classes (course_id, class_name) values ('C0110', 'Practical Ezhill - Class 2');
insert into classes (course_id, class_name) values ('C0111', 'Beginner F# - Class 1');
insert into classes (course_id, class_name) values ('C0111', 'Beginner F# - Class 2');
insert into classes (course_id, class_name) values ('C0112', 'Intermediate F# - Class 1');
insert into classes (course_id, class_name) values ('C0112', 'Intermediate F# - Class 2');
insert into classes (course_id, class_name) values ('C0113', 'Advanced F# - Class 1');
insert into classes (course_id, class_name) values ('C0113', 'Advanced F# - Class 2');
insert into classes (course_id, class_name) values ('C0114', 'Practical F# - Class 1');
insert into classes (course_id, class_name) values ('C0114', 'Practical F# - Class 2');
insert into classes (course_id, class_name) values ('C0115', 'Beginner FAUST - Class 1');
insert into classes (course_id, class_name) values ('C0115', 'Beginner FAUST - Class 2');
insert into classes (course_id, class_name) values ('C0116', 'Intermediate FAUST - Class 1');
insert into classes (course_id, class_name) values ('C0116', 'Intermediate FAUST - Class 2');
insert into classes (course_id, class_name) values ('C0117', 'Advanced FAUST - Class 1');
insert into classes (course_id, class_name) values ('C0117', 'Advanced FAUST - Class 2');
insert into classes (course_id, class_name) values ('C0118', 'Practical FAUST - Class 1');
insert into classes (course_id, class_name) values ('C0118', 'Practical FAUST - Class 2');
insert into classes (course_id, class_name) values ('C0119', 'Beginner FFP - Class 1');
insert into classes (course_id, class_name) values ('C0119', 'Beginner FFP - Class 2');
insert into classes (course_id, class_name) values ('C0120', 'Intermediate FFP - Class 1');
insert into classes (course_id, class_name) values ('C0120', 'Intermediate FFP - Class 2');
insert into classes (course_id, class_name) values ('C0121', 'Advanced FFP - Class 1');
insert into classes (course_id, class_name) values ('C0121', 'Advanced FFP - Class 2');
insert into classes (course_id, class_name) values ('C0122', 'Practical FFP - Class 1');
insert into classes (course_id, class_name) values ('C0122', 'Practical FFP - Class 2');
insert into classes (course_id, class_name) values ('C0123', 'Beginner Fjolnir - Class 1');
insert into classes (course_id, class_name) values ('C0123', 'Beginner Fjolnir - Class 2');
insert into classes (course_id, class_name) values ('C0124', 'Intermediate Fjolnir - Class 1');
insert into classes (course_id, class_name) values ('C0124', 'Intermediate Fjolnir - Class 2');
insert into classes (course_id, class_name) values ('C0125', 'Advanced Fjolnir - Class 1');
insert into classes (course_id, class_name) values ('C0125', 'Advanced Fjolnir - Class 2');
insert into classes (course_id, class_name) values ('C0126', 'Practical Fjolnir - Class 1');
insert into classes (course_id, class_name) values ('C0126', 'Practical Fjolnir - Class 2');
insert into classes (course_id, class_name) values ('C0127', 'Beginner FORMAC - Class 1');
insert into classes (course_id, class_name) values ('C0127', 'Beginner FORMAC - Class 2');
insert into classes (course_id, class_name) values ('C0128', 'Intermediate FORMAC - Class 1');
insert into classes (course_id, class_name) values ('C0128', 'Intermediate FORMAC - Class 2');
insert into classes (course_id, class_name) values ('C0129', 'Advanced FORMAC - Class 1');
insert into classes (course_id, class_name) values ('C0129', 'Advanced FORMAC - Class 2');
insert into classes (course_id, class_name) values ('C0130', 'Practical FORMAC - Class 1');
insert into classes (course_id, class_name) values ('C0130', 'Practical FORMAC - Class 2');
insert into classes (course_id, class_name) values ('C0131', 'Beginner F-SCRIPT - Class 1');
insert into classes (course_id, class_name) values ('C0131', 'Beginner F-SCRIPT - Class 2');
insert into classes (course_id, class_name) values ('C0132', 'Intermediate F-SCRIPT - Class 1');
insert into classes (course_id, class_name) values ('C0132', 'Intermediate F-SCRIPT - Class 2');
insert into classes (course_id, class_name) values ('C0133', 'Advanced F-SCRIPT - Class 1');
insert into classes (course_id, class_name) values ('C0133', 'Advanced F-SCRIPT - Class 2');
insert into classes (course_id, class_name) values ('C0134', 'Practical F-SCRIPT - Class 1');
insert into classes (course_id, class_name) values ('C0134', 'Practical F-SCRIPT - Class 2');
insert into classes (course_id, class_name) values ('C0135', 'Beginner FURTHARK - Class 1');
insert into classes (course_id, class_name) values ('C0135', 'Beginner FURTHARK - Class 2');
insert into classes (course_id, class_name) values ('C0136', 'Intermediate FURTHARK - Class 1');
insert into classes (course_id, class_name) values ('C0136', 'Intermediate FURTHARK - Class 2');
insert into classes (course_id, class_name) values ('C0137', 'Advanced FURTHARK - Class 1');
insert into classes (course_id, class_name) values ('C0137', 'Advanced FURTHARK - Class 2');
insert into classes (course_id, class_name) values ('C0138', 'Practical FURTHARK - Class 1');
insert into classes (course_id, class_name) values ('C0138', 'Practical FURTHARK - Class 2');
insert into classes (course_id, class_name) values ('C0139', 'Beginner Fortran ISO/IEC 1539 - Class 1');
insert into classes (course_id, class_name) values ('C0139', 'Beginner Fortran ISO/IEC 1539 - Class 2');
insert into classes (course_id, class_name) values ('C0140', 'Intermediate Fortran ISO/IEC 1539 - Class 1');
insert into classes (course_id, class_name) values ('C0140', 'Intermediate Fortran ISO/IEC 1539 - Class 2');
insert into classes (course_id, class_name) values ('C0141', 'Advanced Fortran ISO/IEC 1539 - Class 1');
insert into classes (course_id, class_name) values ('C0141', 'Advanced Fortran ISO/IEC 1539 - Class 2');
insert into classes (course_id, class_name) values ('C0142', 'Practical Fortran ISO/IEC 1539 - Class 1');
insert into classes (course_id, class_name) values ('C0142', 'Practical Fortran ISO/IEC 1539 - Class 2');
insert into classes (course_id, class_name) values ('C0143', 'Beginner Firebase - Class 1');
insert into classes (course_id, class_name) values ('C0143', 'Beginner Firebase - Class 2');
insert into classes (course_id, class_name) values ('C0144', 'Intermediate Firebase - Class 1');
insert into classes (course_id, class_name) values ('C0144', 'Intermediate Firebase - Class 2');
insert into classes (course_id, class_name) values ('C0145', 'Advanced Firebase - Class 1');
insert into classes (course_id, class_name) values ('C0145', 'Advanced Firebase - Class 2');
insert into classes (course_id, class_name) values ('C0146', 'Practical Firebase - Class 1');
insert into classes (course_id, class_name) values ('C0146', 'Practical Firebase - Class 2');
insert into classes (course_id, class_name) values ('C0147', 'Beginner GameMonkey Script - Class 1');
insert into classes (course_id, class_name) values ('C0147', 'Beginner GameMonkey Script - Class 2');
insert into classes (course_id, class_name) values ('C0148', 'Intermediate GameMonkey Script - Class 1');
insert into classes (course_id, class_name) values ('C0148', 'Intermediate GameMonkey Script - Class 2');
insert into classes (course_id, class_name) values ('C0149', 'Advanced GameMonkey Script - Class 1');
insert into classes (course_id, class_name) values ('C0149', 'Advanced GameMonkey Script - Class 2');
insert into classes (course_id, class_name) values ('C0150', 'Practical GameMonkey Script - Class 1');
insert into classes (course_id, class_name) values ('C0150', 'Practical GameMonkey Script - Class 2');
insert into classes (course_id, class_name) values ('C0151', 'Beginner GAMS - Class 1');
insert into classes (course_id, class_name) values ('C0151', 'Beginner GAMS - Class 2');
insert into classes (course_id, class_name) values ('C0152', 'Intermediate GAMS - Class 1');
insert into classes (course_id, class_name) values ('C0152', 'Intermediate GAMS - Class 2');
insert into classes (course_id, class_name) values ('C0153', 'Advanced GAMS - Class 1');
insert into classes (course_id, class_name) values ('C0153', 'Advanced GAMS - Class 2');
insert into classes (course_id, class_name) values ('C0154', 'Practical GAMS - Class 1');
insert into classes (course_id, class_name) values ('C0154', 'Practical GAMS - Class 2');
insert into classes (course_id, class_name) values ('C0155', 'Beginner G-code - Class 1');
insert into classes (course_id, class_name) values ('C0155', 'Beginner G-code - Class 2');
insert into classes (course_id, class_name) values ('C0156', 'Intermediate G-code - Class 1');
insert into classes (course_id, class_name) values ('C0156', 'Intermediate G-code - Class 2');
insert into classes (course_id, class_name) values ('C0157', 'Advanced G-code - Class 1');
insert into classes (course_id, class_name) values ('C0157', 'Advanced G-code - Class 2');
insert into classes (course_id, class_name) values ('C0158', 'Practical G-code - Class 1');
insert into classes (course_id, class_name) values ('C0158', 'Practical G-code - Class 2');
insert into classes (course_id, class_name) values ('C0159', 'Beginner GIT - Class 1');
insert into classes (course_id, class_name) values ('C0159', 'Beginner GIT - Class 2');
insert into classes (course_id, class_name) values ('C0160', 'Intermediate GIT - Class 1');
insert into classes (course_id, class_name) values ('C0160', 'Intermediate GIT - Class 2');
insert into classes (course_id, class_name) values ('C0161', 'Advanced GIT - Class 1');
insert into classes (course_id, class_name) values ('C0161', 'Advanced GIT - Class 2');
insert into classes (course_id, class_name) values ('C0162', 'Practical GIT - Class 1');
insert into classes (course_id, class_name) values ('C0162', 'Practical GIT - Class 2');
insert into classes (course_id, class_name) values ('C0163', 'Beginner GNU E - Class 1');
insert into classes (course_id, class_name) values ('C0163', 'Beginner GNU E - Class 2');
insert into classes (course_id, class_name) values ('C0164', 'Intermediate GNU E - Class 1');
insert into classes (course_id, class_name) values ('C0164', 'Intermediate GNU E - Class 2');
insert into classes (course_id, class_name) values ('C0165', 'Advanced GNU E - Class 1');
insert into classes (course_id, class_name) values ('C0165', 'Advanced GNU E - Class 2');
insert into classes (course_id, class_name) values ('C0166', 'Practical GNU E - Class 1');
insert into classes (course_id, class_name) values ('C0166', 'Practical GNU E - Class 2');
insert into classes (course_id, class_name) values ('C0167', 'Beginner GNU Guile - Class 1');
insert into classes (course_id, class_name) values ('C0167', 'Beginner GNU Guile - Class 2');
insert into classes (course_id, class_name) values ('C0168', 'Intermediate GNU Guile - Class 1');
insert into classes (course_id, class_name) values ('C0168', 'Intermediate GNU Guile - Class 2');
insert into classes (course_id, class_name) values ('C0169', 'Advanced GNU Guile - Class 1');
insert into classes (course_id, class_name) values ('C0169', 'Advanced GNU Guile - Class 2');
insert into classes (course_id, class_name) values ('C0170', 'Practical GNU Guile - Class 1');
insert into classes (course_id, class_name) values ('C0170', 'Practical GNU Guile - Class 2');
insert into classes (course_id, class_name) values ('C0171', 'Beginner Google Apps Script - Class 1');
insert into classes (course_id, class_name) values ('C0171', 'Beginner Google Apps Script - Class 2');
insert into classes (course_id, class_name) values ('C0172', 'Intermediate Google Apps Script - Class 1');
insert into classes (course_id, class_name) values ('C0172', 'Intermediate Google Apps Script - Class 2');
insert into classes (course_id, class_name) values ('C0173', 'Advanced Google Apps Script - Class 1');
insert into classes (course_id, class_name) values ('C0173', 'Advanced Google Apps Script - Class 2');
insert into classes (course_id, class_name) values ('C0174', 'Practical Google Apps Script - Class 1');
insert into classes (course_id, class_name) values ('C0174', 'Practical Google Apps Script - Class 2');
insert into classes (course_id, class_name) values ('C0175', 'Beginner GraphTalk - Class 1');
insert into classes (course_id, class_name) values ('C0175', 'Beginner GraphTalk - Class 2');
insert into classes (course_id, class_name) values ('C0176', 'Intermediate GraphTalk - Class 1');
insert into classes (course_id, class_name) values ('C0176', 'Intermediate GraphTalk - Class 2');
insert into classes (course_id, class_name) values ('C0177', 'Advanced GraphTalk - Class 1');
insert into classes (course_id, class_name) values ('C0177', 'Advanced GraphTalk - Class 2');
insert into classes (course_id, class_name) values ('C0178', 'Practical GraphTalk - Class 1');
insert into classes (course_id, class_name) values ('C0178', 'Practical GraphTalk - Class 2');
insert into classes (course_id, class_name) values ('C0179', 'Beginner HTML - Class 1');
insert into classes (course_id, class_name) values ('C0179', 'Beginner HTML - Class 2');
insert into classes (course_id, class_name) values ('C0180', 'Intermediate HTML - Class 1');
insert into classes (course_id, class_name) values ('C0180', 'Intermediate HTML - Class 2');
insert into classes (course_id, class_name) values ('C0181', 'Advanced HTML - Class 1');
insert into classes (course_id, class_name) values ('C0181', 'Advanced HTML - Class 2');
insert into classes (course_id, class_name) values ('C0182', 'Practical HTML - Class 1');
insert into classes (course_id, class_name) values ('C0182', 'Practical HTML - Class 2');
insert into classes (course_id, class_name) values ('C0183', 'Beginner Hack - Class 1');
insert into classes (course_id, class_name) values ('C0183', 'Beginner Hack - Class 2');
insert into classes (course_id, class_name) values ('C0184', 'Intermediate Hack - Class 1');
insert into classes (course_id, class_name) values ('C0184', 'Intermediate Hack - Class 2');
insert into classes (course_id, class_name) values ('C0185', 'Advanced Hack - Class 1');
insert into classes (course_id, class_name) values ('C0185', 'Advanced Hack - Class 2');
insert into classes (course_id, class_name) values ('C0186', 'Practical Hack - Class 1');
insert into classes (course_id, class_name) values ('C0186', 'Practical Hack - Class 2');
insert into classes (course_id, class_name) values ('C0187', 'Beginner Hamilton C Shell - Class 1');
insert into classes (course_id, class_name) values ('C0187', 'Beginner Hamilton C Shell - Class 2');
insert into classes (course_id, class_name) values ('C0188', 'Intermediate Hamilton C Shell - Class 1');
insert into classes (course_id, class_name) values ('C0188', 'Intermediate Hamilton C Shell - Class 2');
insert into classes (course_id, class_name) values ('C0189', 'Advanced Hamilton C Shell - Class 1');
insert into classes (course_id, class_name) values ('C0189', 'Advanced Hamilton C Shell - Class 2');
insert into classes (course_id, class_name) values ('C0190', 'Practical Hamilton C Shell - Class 1');
insert into classes (course_id, class_name) values ('C0190', 'Practical Hamilton C Shell - Class 2');
insert into classes (course_id, class_name) values ('C0191', 'Beginner Hartmann pipelines - Class 1');
insert into classes (course_id, class_name) values ('C0191', 'Beginner Hartmann pipelines - Class 2');
insert into classes (course_id, class_name) values ('C0192', 'Intermediate Hartmann pipelines - Class 1');
insert into classes (course_id, class_name) values ('C0192', 'Intermediate Hartmann pipelines - Class 2');
insert into classes (course_id, class_name) values ('C0193', 'Advanced Hartmann pipelines - Class 1');
insert into classes (course_id, class_name) values ('C0193', 'Advanced Hartmann pipelines - Class 2');
insert into classes (course_id, class_name) values ('C0194', 'Practical Hartmann pipelines - Class 1');
insert into classes (course_id, class_name) values ('C0194', 'Practical Hartmann pipelines - Class 2');
insert into classes (course_id, class_name) values ('C0195', 'Beginner Haskell - Class 1');
insert into classes (course_id, class_name) values ('C0195', 'Beginner Haskell - Class 2');
insert into classes (course_id, class_name) values ('C0196', 'Intermediate Haskell - Class 1');
insert into classes (course_id, class_name) values ('C0196', 'Intermediate Haskell - Class 2');
insert into classes (course_id, class_name) values ('C0197', 'Advanced Haskell - Class 1');
insert into classes (course_id, class_name) values ('C0197', 'Advanced Haskell - Class 2');
insert into classes (course_id, class_name) values ('C0198', 'Practical Haskell - Class 1');
insert into classes (course_id, class_name) values ('C0198', 'Practical Haskell - Class 2');
insert into classes (course_id, class_name) values ('C0199', 'Beginner Haxe - Class 1');
insert into classes (course_id, class_name) values ('C0199', 'Beginner Haxe - Class 2');
insert into classes (course_id, class_name) values ('C0200', 'Intermediate Haxe - Class 1');
insert into classes (course_id, class_name) values ('C0200', 'Intermediate Haxe - Class 2');
insert into classes (course_id, class_name) values ('C0201', 'Advanced Haxe - Class 1');
insert into classes (course_id, class_name) values ('C0201', 'Advanced Haxe - Class 2');
insert into classes (course_id, class_name) values ('C0202', 'Practical Haxe - Class 1');
insert into classes (course_id, class_name) values ('C0202', 'Practical Haxe - Class 2');
insert into classes (course_id, class_name) values ('C0203', 'Beginner High Level Assembly - Class 1');
insert into classes (course_id, class_name) values ('C0203', 'Beginner High Level Assembly - Class 2');
insert into classes (course_id, class_name) values ('C0204', 'Intermediate High Level Assembly - Class 1');
insert into classes (course_id, class_name) values ('C0204', 'Intermediate High Level Assembly - Class 2');
insert into classes (course_id, class_name) values ('C0205', 'Advanced High Level Assembly - Class 1');
insert into classes (course_id, class_name) values ('C0205', 'Advanced High Level Assembly - Class 2');
insert into classes (course_id, class_name) values ('C0206', 'Practical High Level Assembly - Class 1');
insert into classes (course_id, class_name) values ('C0206', 'Practical High Level Assembly - Class 2');
insert into classes (course_id, class_name) values ('C0207', 'Beginner HolyC - Class 1');
insert into classes (course_id, class_name) values ('C0207', 'Beginner HolyC - Class 2');
insert into classes (course_id, class_name) values ('C0208', 'Intermediate HolyC - Class 1');
insert into classes (course_id, class_name) values ('C0208', 'Intermediate HolyC - Class 2');
insert into classes (course_id, class_name) values ('C0209', 'Advanced HolyC - Class 1');
insert into classes (course_id, class_name) values ('C0209', 'Advanced HolyC - Class 2');
insert into classes (course_id, class_name) values ('C0210', 'Practical HolyC - Class 1');
insert into classes (course_id, class_name) values ('C0210', 'Practical HolyC - Class 2');
insert into classes (course_id, class_name) values ('C0211', 'Beginner IBM basic assembly language - Class 1');
insert into classes (course_id, class_name) values ('C0211', 'Beginner IBM basic assembly language - Class 2');
insert into classes (course_id, class_name) values ('C0212', 'Intermediate IBM basic assembly language - Class 1');
insert into classes (course_id, class_name) values ('C0212', 'Intermediate IBM basic assembly language - Class 2');
insert into classes (course_id, class_name) values ('C0213', 'Advanced IBM basic assembly language - Class 1');
insert into classes (course_id, class_name) values ('C0213', 'Advanced IBM basic assembly language - Class 2');
insert into classes (course_id, class_name) values ('C0214', 'Practical IBM basic assembly language - Class 1');
insert into classes (course_id, class_name) values ('C0214', 'Practical IBM basic assembly language - Class 2');
insert into classes (course_id, class_name) values ('C0215', 'Beginner IBM HAScript - Class 1');
insert into classes (course_id, class_name) values ('C0215', 'Beginner IBM HAScript - Class 2');
insert into classes (course_id, class_name) values ('C0216', 'Intermediate IBM HAScript - Class 1');
insert into classes (course_id, class_name) values ('C0216', 'Intermediate IBM HAScript - Class 2');
insert into classes (course_id, class_name) values ('C0217', 'Advanced IBM HAScript - Class 1');
insert into classes (course_id, class_name) values ('C0217', 'Advanced IBM HAScript - Class 2');
insert into classes (course_id, class_name) values ('C0218', 'Practical IBM HAScript - Class 1');
insert into classes (course_id, class_name) values ('C0218', 'Practical IBM HAScript - Class 2');
insert into classes (course_id, class_name) values ('C0219', 'Beginner IBM informix-4GL - Class 1');
insert into classes (course_id, class_name) values ('C0219', 'Beginner IBM informix-4GL - Class 2');
insert into classes (course_id, class_name) values ('C0220', 'Intermediate IBM informix-4GL - Class 1');
insert into classes (course_id, class_name) values ('C0220', 'Intermediate IBM informix-4GL - Class 2');
insert into classes (course_id, class_name) values ('C0221', 'Advanced IBM informix-4GL - Class 1');
insert into classes (course_id, class_name) values ('C0221', 'Advanced IBM informix-4GL - Class 2');
insert into classes (course_id, class_name) values ('C0222', 'Practical IBM informix-4GL - Class 1');
insert into classes (course_id, class_name) values ('C0222', 'Practical IBM informix-4GL - Class 2');
insert into classes (course_id, class_name) values ('C0223', 'Beginner IBM RPG - Class 1');
insert into classes (course_id, class_name) values ('C0223', 'Beginner IBM RPG - Class 2');
insert into classes (course_id, class_name) values ('C0224', 'Intermediate IBM RPG - Class 1');
insert into classes (course_id, class_name) values ('C0224', 'Intermediate IBM RPG - Class 2');
insert into classes (course_id, class_name) values ('C0225', 'Advanced IBM RPG - Class 1');
insert into classes (course_id, class_name) values ('C0225', 'Advanced IBM RPG - Class 2');
insert into classes (course_id, class_name) values ('C0226', 'Practical IBM RPG - Class 1');
insert into classes (course_id, class_name) values ('C0226', 'Practical IBM RPG - Class 2');
insert into classes (course_id, class_name) values ('C0227', 'Beginner IDL - Class 1');
insert into classes (course_id, class_name) values ('C0227', 'Beginner IDL - Class 2');
insert into classes (course_id, class_name) values ('C0228', 'Intermediate IDL - Class 1');
insert into classes (course_id, class_name) values ('C0228', 'Intermediate IDL - Class 2');
insert into classes (course_id, class_name) values ('C0229', 'Advanced IDL - Class 1');
insert into classes (course_id, class_name) values ('C0229', 'Advanced IDL - Class 2');
insert into classes (course_id, class_name) values ('C0230', 'Practical IDL - Class 1');
insert into classes (course_id, class_name) values ('C0230', 'Practical IDL - Class 2');
insert into classes (course_id, class_name) values ('C0231', 'Beginner J# - Class 1');
insert into classes (course_id, class_name) values ('C0231', 'Beginner J# - Class 2');
insert into classes (course_id, class_name) values ('C0232', 'Intermediate J# - Class 1');
insert into classes (course_id, class_name) values ('C0232', 'Intermediate J# - Class 2');
insert into classes (course_id, class_name) values ('C0233', 'Advanced J# - Class 1');
insert into classes (course_id, class_name) values ('C0233', 'Advanced J# - Class 2');
insert into classes (course_id, class_name) values ('C0234', 'Practical J# - Class 1');
insert into classes (course_id, class_name) values ('C0234', 'Practical J# - Class 2');
insert into classes (course_id, class_name) values ('C0235', 'Beginner JADE - Class 1');
insert into classes (course_id, class_name) values ('C0235', 'Beginner JADE - Class 2');
insert into classes (course_id, class_name) values ('C0236', 'Intermediate JADE - Class 1');
insert into classes (course_id, class_name) values ('C0236', 'Intermediate JADE - Class 2');
insert into classes (course_id, class_name) values ('C0237', 'Advanced JADE - Class 1');
insert into classes (course_id, class_name) values ('C0237', 'Advanced JADE - Class 2');
insert into classes (course_id, class_name) values ('C0238', 'Practical JADE - Class 1');
insert into classes (course_id, class_name) values ('C0238', 'Practical JADE - Class 2');
insert into classes (course_id, class_name) values ('C0239', 'Beginner Java - Class 1');
insert into classes (course_id, class_name) values ('C0239', 'Beginner Java - Class 2');
insert into classes (course_id, class_name) values ('C0240', 'Intermediate Java - Class 1');
insert into classes (course_id, class_name) values ('C0240', 'Intermediate Java - Class 2');
insert into classes (course_id, class_name) values ('C0241', 'Advanced Java - Class 1');
insert into classes (course_id, class_name) values ('C0241', 'Advanced Java - Class 2');
insert into classes (course_id, class_name) values ('C0242', 'Practical Java - Class 1');
insert into classes (course_id, class_name) values ('C0242', 'Practical Java - Class 2');
insert into classes (course_id, class_name) values ('C0243', 'Beginner JavaFX Script - Class 1');
insert into classes (course_id, class_name) values ('C0243', 'Beginner JavaFX Script - Class 2');
insert into classes (course_id, class_name) values ('C0244', 'Intermediate JavaFX Script - Class 1');
insert into classes (course_id, class_name) values ('C0244', 'Intermediate JavaFX Script - Class 2');
insert into classes (course_id, class_name) values ('C0245', 'Advanced JavaFX Script - Class 1');
insert into classes (course_id, class_name) values ('C0245', 'Advanced JavaFX Script - Class 2');
insert into classes (course_id, class_name) values ('C0246', 'Practical JavaFX Script - Class 1');
insert into classes (course_id, class_name) values ('C0246', 'Practical JavaFX Script - Class 2');
insert into classes (course_id, class_name) values ('C0247', 'Beginner JavaSript - Class 1');
insert into classes (course_id, class_name) values ('C0247', 'Beginner JavaSript - Class 2');
insert into classes (course_id, class_name) values ('C0248', 'Intermediate JavaSript - Class 1');
insert into classes (course_id, class_name) values ('C0248', 'Intermediate JavaSript - Class 2');
insert into classes (course_id, class_name) values ('C0249', 'Advanced JavaSript - Class 1');
insert into classes (course_id, class_name) values ('C0249', 'Advanced JavaSript - Class 2');
insert into classes (course_id, class_name) values ('C0250', 'Practical JavaSript - Class 1');
insert into classes (course_id, class_name) values ('C0250', 'Practical JavaSript - Class 2');
insert into classes (course_id, class_name) values ('C0251', 'Beginner JScript - Class 1');
insert into classes (course_id, class_name) values ('C0251', 'Beginner JScript - Class 2');
insert into classes (course_id, class_name) values ('C0252', 'Intermediate JScript - Class 1');
insert into classes (course_id, class_name) values ('C0252', 'Intermediate JScript - Class 2');
insert into classes (course_id, class_name) values ('C0253', 'Advanced JScript - Class 1');
insert into classes (course_id, class_name) values ('C0253', 'Advanced JScript - Class 2');
insert into classes (course_id, class_name) values ('C0254', 'Practical JScript - Class 1');
insert into classes (course_id, class_name) values ('C0254', 'Practical JScript - Class 2');
insert into classes (course_id, class_name) values ('C0255', 'Beginner JScript .NET - Class 1');
insert into classes (course_id, class_name) values ('C0255', 'Beginner JScript .NET - Class 2');
insert into classes (course_id, class_name) values ('C0256', 'Intermediate JScript .NET - Class 1');
insert into classes (course_id, class_name) values ('C0256', 'Intermediate JScript .NET - Class 2');
insert into classes (course_id, class_name) values ('C0257', 'Advanced JScript .NET - Class 1');
insert into classes (course_id, class_name) values ('C0257', 'Advanced JScript .NET - Class 2');
insert into classes (course_id, class_name) values ('C0258', 'Practical JScript .NET - Class 1');
insert into classes (course_id, class_name) values ('C0258', 'Practical JScript .NET - Class 2');
insert into classes (course_id, class_name) values ('C0259', 'Beginner Jython - Class 1');
insert into classes (course_id, class_name) values ('C0259', 'Beginner Jython - Class 2');
insert into classes (course_id, class_name) values ('C0260', 'Intermediate Jython - Class 1');
insert into classes (course_id, class_name) values ('C0260', 'Intermediate Jython - Class 2');
insert into classes (course_id, class_name) values ('C0261', 'Advanced Jython - Class 1');
insert into classes (course_id, class_name) values ('C0261', 'Advanced Jython - Class 2');
insert into classes (course_id, class_name) values ('C0262', 'Practical Jython - Class 1');
insert into classes (course_id, class_name) values ('C0262', 'Practical Jython - Class 2');
insert into classes (course_id, class_name) values ('C0263', 'Beginner Kotlin - Class 1');
insert into classes (course_id, class_name) values ('C0263', 'Beginner Kotlin - Class 2');
insert into classes (course_id, class_name) values ('C0264', 'Intermediate Kotlin - Class 1');
insert into classes (course_id, class_name) values ('C0264', 'Intermediate Kotlin - Class 2');
insert into classes (course_id, class_name) values ('C0265', 'Advanced Kotlin - Class 1');
insert into classes (course_id, class_name) values ('C0265', 'Advanced Kotlin - Class 2');
insert into classes (course_id, class_name) values ('C0266', 'Practical Kotlin - Class 1');
insert into classes (course_id, class_name) values ('C0266', 'Practical Kotlin - Class 2');
insert into classes (course_id, class_name) values ('C0267', 'Beginner Krypthon - Class 1');
insert into classes (course_id, class_name) values ('C0267', 'Beginner Krypthon - Class 2');
insert into classes (course_id, class_name) values ('C0268', 'Intermediate Krypthon - Class 1');
insert into classes (course_id, class_name) values ('C0268', 'Intermediate Krypthon - Class 2');
insert into classes (course_id, class_name) values ('C0269', 'Advanced Krypthon - Class 1');
insert into classes (course_id, class_name) values ('C0269', 'Advanced Krypthon - Class 2');
insert into classes (course_id, class_name) values ('C0270', 'Practical Krypthon - Class 1');
insert into classes (course_id, class_name) values ('C0270', 'Practical Krypthon - Class 2');
insert into classes (course_id, class_name) values ('C0271', 'Beginner Korn Shell - Class 1');
insert into classes (course_id, class_name) values ('C0271', 'Beginner Korn Shell - Class 2');
insert into classes (course_id, class_name) values ('C0272', 'Intermediate Korn Shell - Class 1');
insert into classes (course_id, class_name) values ('C0272', 'Intermediate Korn Shell - Class 2');
insert into classes (course_id, class_name) values ('C0273', 'Advanced Korn Shell - Class 1');
insert into classes (course_id, class_name) values ('C0273', 'Advanced Korn Shell - Class 2');
insert into classes (course_id, class_name) values ('C0274', 'Practical Korn Shell - Class 1');
insert into classes (course_id, class_name) values ('C0274', 'Practical Korn Shell - Class 2');
insert into classes (course_id, class_name) values ('C0275', 'Beginner LavVIEW - Class 1');
insert into classes (course_id, class_name) values ('C0275', 'Beginner LavVIEW - Class 2');
insert into classes (course_id, class_name) values ('C0276', 'Intermediate LavVIEW - Class 1');
insert into classes (course_id, class_name) values ('C0276', 'Intermediate LavVIEW - Class 2');
insert into classes (course_id, class_name) values ('C0277', 'Advanced LavVIEW - Class 1');
insert into classes (course_id, class_name) values ('C0277', 'Advanced LavVIEW - Class 2');
insert into classes (course_id, class_name) values ('C0278', 'Practical LavVIEW - Class 1');
insert into classes (course_id, class_name) values ('C0278', 'Practical LavVIEW - Class 2');
insert into classes (course_id, class_name) values ('C0279', 'Beginner Ladder - Class 1');
insert into classes (course_id, class_name) values ('C0279', 'Beginner Ladder - Class 2');
insert into classes (course_id, class_name) values ('C0280', 'Intermediate Ladder - Class 1');
insert into classes (course_id, class_name) values ('C0280', 'Intermediate Ladder - Class 2');
insert into classes (course_id, class_name) values ('C0281', 'Advanced Ladder - Class 1');
insert into classes (course_id, class_name) values ('C0281', 'Advanced Ladder - Class 2');
insert into classes (course_id, class_name) values ('C0282', 'Practical Ladder - Class 1');
insert into classes (course_id, class_name) values ('C0282', 'Practical Ladder - Class 2');
insert into classes (course_id, class_name) values ('C0283', 'Beginner LegoScript - Class 1');
insert into classes (course_id, class_name) values ('C0283', 'Beginner LegoScript - Class 2');
insert into classes (course_id, class_name) values ('C0284', 'Intermediate LegoScript - Class 1');
insert into classes (course_id, class_name) values ('C0284', 'Intermediate LegoScript - Class 2');
insert into classes (course_id, class_name) values ('C0285', 'Advanced LegoScript - Class 1');
insert into classes (course_id, class_name) values ('C0285', 'Advanced LegoScript - Class 2');
insert into classes (course_id, class_name) values ('C0286', 'Practical LegoScript - Class 1');
insert into classes (course_id, class_name) values ('C0286', 'Practical LegoScript - Class 2');
insert into classes (course_id, class_name) values ('C0287', 'Beginner LINQ - Class 1');
insert into classes (course_id, class_name) values ('C0287', 'Beginner LINQ - Class 2');
insert into classes (course_id, class_name) values ('C0288', 'Intermediate LINQ - Class 1');
insert into classes (course_id, class_name) values ('C0288', 'Intermediate LINQ - Class 2');
insert into classes (course_id, class_name) values ('C0289', 'Advanced LINQ - Class 1');
insert into classes (course_id, class_name) values ('C0289', 'Advanced LINQ - Class 2');
insert into classes (course_id, class_name) values ('C0290', 'Practical LINQ - Class 1');
insert into classes (course_id, class_name) values ('C0290', 'Practical LINQ - Class 2');
insert into classes (course_id, class_name) values ('C0291', 'Beginner Lite-C - Class 1');
insert into classes (course_id, class_name) values ('C0291', 'Beginner Lite-C - Class 2');
insert into classes (course_id, class_name) values ('C0292', 'Intermediate Lite-C - Class 1');
insert into classes (course_id, class_name) values ('C0292', 'Intermediate Lite-C - Class 2');
insert into classes (course_id, class_name) values ('C0293', 'Advanced Lite-C - Class 1');
insert into classes (course_id, class_name) values ('C0293', 'Advanced Lite-C - Class 2');
insert into classes (course_id, class_name) values ('C0294', 'Practical Lite-C - Class 1');
insert into classes (course_id, class_name) values ('C0294', 'Practical Lite-C - Class 2');
insert into classes (course_id, class_name) values ('C0295', 'Beginner LotusScript - Class 1');
insert into classes (course_id, class_name) values ('C0295', 'Beginner LotusScript - Class 2');
insert into classes (course_id, class_name) values ('C0296', 'Intermediate LotusScript - Class 1');
insert into classes (course_id, class_name) values ('C0296', 'Intermediate LotusScript - Class 2');
insert into classes (course_id, class_name) values ('C0297', 'Advanced LotusScript - Class 1');
insert into classes (course_id, class_name) values ('C0297', 'Advanced LotusScript - Class 2');
insert into classes (course_id, class_name) values ('C0298', 'Practical LotusScript - Class 1');
insert into classes (course_id, class_name) values ('C0298', 'Practical LotusScript - Class 2');
insert into classes (course_id, class_name) values ('C0299', 'Beginner Lua - Class 1');
insert into classes (course_id, class_name) values ('C0299', 'Beginner Lua - Class 2');
insert into classes (course_id, class_name) values ('C0300', 'Intermediate Lua - Class 1');
insert into classes (course_id, class_name) values ('C0300', 'Intermediate Lua - Class 2');
insert into classes (course_id, class_name) values ('C0301', 'Advanced Lua - Class 1');
insert into classes (course_id, class_name) values ('C0301', 'Advanced Lua - Class 2');
insert into classes (course_id, class_name) values ('C0302', 'Practical Lua - Class 1');
insert into classes (course_id, class_name) values ('C0302', 'Practical Lua - Class 2');
insert into classes (course_id, class_name) values ('C0303', 'Beginner LYaPAS - Class 1');
insert into classes (course_id, class_name) values ('C0303', 'Beginner LYaPAS - Class 2');
insert into classes (course_id, class_name) values ('C0304', 'Intermediate LYaPAS - Class 1');
insert into classes (course_id, class_name) values ('C0304', 'Intermediate LYaPAS - Class 2');
insert into classes (course_id, class_name) values ('C0305', 'Advanced LYaPAS - Class 1');
insert into classes (course_id, class_name) values ('C0305', 'Advanced LYaPAS - Class 2');
insert into classes (course_id, class_name) values ('C0306', 'Practical LYaPAS - Class 1');
insert into classes (course_id, class_name) values ('C0306', 'Practical LYaPAS - Class 2');
insert into classes (course_id, class_name) values ('C0307', 'Beginner MASM Microsoft Assembly x86 - Class 1');
insert into classes (course_id, class_name) values ('C0307', 'Beginner MASM Microsoft Assembly x86 - Class 2');
insert into classes (course_id, class_name) values ('C0308', 'Intermediate MASM Microsoft Assembly x86 - Class 1');
insert into classes (course_id, class_name) values ('C0308', 'Intermediate MASM Microsoft Assembly x86 - Class 2');
insert into classes (course_id, class_name) values ('C0309', 'Advanced MASM Microsoft Assembly x86 - Class 1');
insert into classes (course_id, class_name) values ('C0309', 'Advanced MASM Microsoft Assembly x86 - Class 2');
insert into classes (course_id, class_name) values ('C0310', 'Practical MASM Microsoft Assembly x86 - Class 1');
insert into classes (course_id, class_name) values ('C0310', 'Practical MASM Microsoft Assembly x86 - Class 2');
insert into classes (course_id, class_name) values ('C0311', 'Beginner Math-Matic - Class 1');
insert into classes (course_id, class_name) values ('C0311', 'Beginner Math-Matic - Class 2');
insert into classes (course_id, class_name) values ('C0312', 'Intermediate Math-Matic - Class 1');
insert into classes (course_id, class_name) values ('C0312', 'Intermediate Math-Matic - Class 2');
insert into classes (course_id, class_name) values ('C0313', 'Advanced Math-Matic - Class 1');
insert into classes (course_id, class_name) values ('C0313', 'Advanced Math-Matic - Class 2');
insert into classes (course_id, class_name) values ('C0314', 'Practical Math-Matic - Class 1');
insert into classes (course_id, class_name) values ('C0314', 'Practical Math-Matic - Class 2');
insert into classes (course_id, class_name) values ('C0315', 'Beginner Maude System - Class 1');
insert into classes (course_id, class_name) values ('C0315', 'Beginner Maude System - Class 2');
insert into classes (course_id, class_name) values ('C0316', 'Intermediate Maude System - Class 1');
insert into classes (course_id, class_name) values ('C0316', 'Intermediate Maude System - Class 2');
insert into classes (course_id, class_name) values ('C0317', 'Advanced Maude System - Class 1');
insert into classes (course_id, class_name) values ('C0317', 'Advanced Maude System - Class 2');
insert into classes (course_id, class_name) values ('C0318', 'Practical Maude System - Class 1');
insert into classes (course_id, class_name) values ('C0318', 'Practical Maude System - Class 2');
insert into classes (course_id, class_name) values ('C0319', 'Beginner Net.Data - Class 1');
insert into classes (course_id, class_name) values ('C0319', 'Beginner Net.Data - Class 2');
insert into classes (course_id, class_name) values ('C0320', 'Intermediate Net.Data - Class 1');
insert into classes (course_id, class_name) values ('C0320', 'Intermediate Net.Data - Class 2');
insert into classes (course_id, class_name) values ('C0321', 'Advanced Net.Data - Class 1');
insert into classes (course_id, class_name) values ('C0321', 'Advanced Net.Data - Class 2');
insert into classes (course_id, class_name) values ('C0322', 'Practical Net.Data - Class 1');
insert into classes (course_id, class_name) values ('C0322', 'Practical Net.Data - Class 2');
insert into classes (course_id, class_name) values ('C0323', 'Beginner NewtonScript - Class 1');
insert into classes (course_id, class_name) values ('C0323', 'Beginner NewtonScript - Class 2');
insert into classes (course_id, class_name) values ('C0324', 'Intermediate NewtonScript - Class 1');
insert into classes (course_id, class_name) values ('C0324', 'Intermediate NewtonScript - Class 2');
insert into classes (course_id, class_name) values ('C0325', 'Advanced NewtonScript - Class 1');
insert into classes (course_id, class_name) values ('C0325', 'Advanced NewtonScript - Class 2');
insert into classes (course_id, class_name) values ('C0326', 'Practical NewtonScript - Class 1');
insert into classes (course_id, class_name) values ('C0326', 'Practical NewtonScript - Class 2');
insert into classes (course_id, class_name) values ('C0327', 'Beginner Object Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0327', 'Beginner Object Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0328', 'Intermediate Object Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0328', 'Intermediate Object Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0329', 'Advanced Object Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0329', 'Advanced Object Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0330', 'Practical Object Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0330', 'Practical Object Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0331', 'Beginner Objective C - Class 1');
insert into classes (course_id, class_name) values ('C0331', 'Beginner Objective C - Class 2');
insert into classes (course_id, class_name) values ('C0332', 'Intermediate Objective C - Class 1');
insert into classes (course_id, class_name) values ('C0332', 'Intermediate Objective C - Class 2');
insert into classes (course_id, class_name) values ('C0333', 'Advanced Objective C - Class 1');
insert into classes (course_id, class_name) values ('C0333', 'Advanced Objective C - Class 2');
insert into classes (course_id, class_name) values ('C0334', 'Practical Objective C - Class 1');
insert into classes (course_id, class_name) values ('C0334', 'Practical Objective C - Class 2');
insert into classes (course_id, class_name) values ('C0335', 'Beginner OpenCL - Class 1');
insert into classes (course_id, class_name) values ('C0335', 'Beginner OpenCL - Class 2');
insert into classes (course_id, class_name) values ('C0336', 'Intermediate OpenCL - Class 1');
insert into classes (course_id, class_name) values ('C0336', 'Intermediate OpenCL - Class 2');
insert into classes (course_id, class_name) values ('C0337', 'Advanced OpenCL - Class 1');
insert into classes (course_id, class_name) values ('C0337', 'Advanced OpenCL - Class 2');
insert into classes (course_id, class_name) values ('C0338', 'Practical OpenCL - Class 1');
insert into classes (course_id, class_name) values ('C0338', 'Practical OpenCL - Class 2');
insert into classes (course_id, class_name) values ('C0339', 'Beginner Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0339', 'Beginner Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0340', 'Intermediate Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0340', 'Intermediate Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0341', 'Advanced Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0341', 'Advanced Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0342', 'Practical Pascal - Class 1');
insert into classes (course_id, class_name) values ('C0342', 'Practical Pascal - Class 2');
insert into classes (course_id, class_name) values ('C0343', 'Beginner Pascal Script - Class 1');
insert into classes (course_id, class_name) values ('C0343', 'Beginner Pascal Script - Class 2');
insert into classes (course_id, class_name) values ('C0344', 'Intermediate Pascal Script - Class 1');
insert into classes (course_id, class_name) values ('C0344', 'Intermediate Pascal Script - Class 2');
insert into classes (course_id, class_name) values ('C0345', 'Advanced Pascal Script - Class 1');
insert into classes (course_id, class_name) values ('C0345', 'Advanced Pascal Script - Class 2');
insert into classes (course_id, class_name) values ('C0346', 'Practical Pascal Script - Class 1');
insert into classes (course_id, class_name) values ('C0346', 'Practical Pascal Script - Class 2');
insert into classes (course_id, class_name) values ('C0347', 'Beginner Pearl - Class 1');
insert into classes (course_id, class_name) values ('C0347', 'Beginner Pearl - Class 2');
insert into classes (course_id, class_name) values ('C0348', 'Intermediate Pearl - Class 1');
insert into classes (course_id, class_name) values ('C0348', 'Intermediate Pearl - Class 2');
insert into classes (course_id, class_name) values ('C0349', 'Advanced Pearl - Class 1');
insert into classes (course_id, class_name) values ('C0349', 'Advanced Pearl - Class 2');
insert into classes (course_id, class_name) values ('C0350', 'Practical Pearl - Class 1');
insert into classes (course_id, class_name) values ('C0350', 'Practical Pearl - Class 2');
insert into classes (course_id, class_name) values ('C0351', 'Beginner PHP - Class 1');
insert into classes (course_id, class_name) values ('C0351', 'Beginner PHP - Class 2');
insert into classes (course_id, class_name) values ('C0352', 'Intermediate PHP - Class 1');
insert into classes (course_id, class_name) values ('C0352', 'Intermediate PHP - Class 2');
insert into classes (course_id, class_name) values ('C0353', 'Advanced PHP - Class 1');
insert into classes (course_id, class_name) values ('C0353', 'Advanced PHP - Class 2');
insert into classes (course_id, class_name) values ('C0354', 'Practical PHP - Class 1');
insert into classes (course_id, class_name) values ('C0354', 'Practical PHP - Class 2');
insert into classes (course_id, class_name) values ('C0355', 'Beginner PL/SQL - Class 1');
insert into classes (course_id, class_name) values ('C0355', 'Beginner PL/SQL - Class 2');
insert into classes (course_id, class_name) values ('C0356', 'Intermediate PL/SQL - Class 1');
insert into classes (course_id, class_name) values ('C0356', 'Intermediate PL/SQL - Class 2');
insert into classes (course_id, class_name) values ('C0357', 'Advanced PL/SQL - Class 1');
insert into classes (course_id, class_name) values ('C0357', 'Advanced PL/SQL - Class 2');
insert into classes (course_id, class_name) values ('C0358', 'Practical PL/SQL - Class 1');
insert into classes (course_id, class_name) values ('C0358', 'Practical PL/SQL - Class 2');
insert into classes (course_id, class_name) values ('C0359', 'Beginner PowerShell - Class 1');
insert into classes (course_id, class_name) values ('C0359', 'Beginner PowerShell - Class 2');
insert into classes (course_id, class_name) values ('C0360', 'Intermediate PowerShell - Class 1');
insert into classes (course_id, class_name) values ('C0360', 'Intermediate PowerShell - Class 2');
insert into classes (course_id, class_name) values ('C0361', 'Advanced PowerShell - Class 1');
insert into classes (course_id, class_name) values ('C0361', 'Advanced PowerShell - Class 2');
insert into classes (course_id, class_name) values ('C0362', 'Practical PowerShell - Class 1');
insert into classes (course_id, class_name) values ('C0362', 'Practical PowerShell - Class 2');
insert into classes (course_id, class_name) values ('C0363', 'Beginner Python - Class 1');
insert into classes (course_id, class_name) values ('C0363', 'Beginner Python - Class 2');
insert into classes (course_id, class_name) values ('C0364', 'Intermediate Python - Class 1');
insert into classes (course_id, class_name) values ('C0364', 'Intermediate Python - Class 2');
insert into classes (course_id, class_name) values ('C0365', 'Advanced Python - Class 1');
insert into classes (course_id, class_name) values ('C0365', 'Advanced Python - Class 2');
insert into classes (course_id, class_name) values ('C0366', 'Practical Python - Class 1');
insert into classes (course_id, class_name) values ('C0366', 'Practical Python - Class 2');
insert into classes (course_id, class_name) values ('C0367', 'Beginner QBasic - Class 1');
insert into classes (course_id, class_name) values ('C0367', 'Beginner QBasic - Class 2');
insert into classes (course_id, class_name) values ('C0368', 'Intermediate QBasic - Class 1');
insert into classes (course_id, class_name) values ('C0368', 'Intermediate QBasic - Class 2');
insert into classes (course_id, class_name) values ('C0369', 'Advanced QBasic - Class 1');
insert into classes (course_id, class_name) values ('C0369', 'Advanced QBasic - Class 2');
insert into classes (course_id, class_name) values ('C0370', 'Practical QBasic - Class 1');
insert into classes (course_id, class_name) values ('C0370', 'Practical QBasic - Class 2');
insert into classes (course_id, class_name) values ('C0371', 'Beginner Ruby - Class 1');
insert into classes (course_id, class_name) values ('C0371', 'Beginner Ruby - Class 2');
insert into classes (course_id, class_name) values ('C0372', 'Intermediate Ruby - Class 1');
insert into classes (course_id, class_name) values ('C0372', 'Intermediate Ruby - Class 2');
insert into classes (course_id, class_name) values ('C0373', 'Advanced Ruby - Class 1');
insert into classes (course_id, class_name) values ('C0373', 'Advanced Ruby - Class 2');
insert into classes (course_id, class_name) values ('C0374', 'Practical Ruby - Class 1');
insert into classes (course_id, class_name) values ('C0374', 'Practical Ruby - Class 2');
insert into classes (course_id, class_name) values ('C0375', 'Beginner Script.NET - Class 1');
insert into classes (course_id, class_name) values ('C0375', 'Beginner Script.NET - Class 2');
insert into classes (course_id, class_name) values ('C0376', 'Intermediate Script.NET - Class 1');
insert into classes (course_id, class_name) values ('C0376', 'Intermediate Script.NET - Class 2');
insert into classes (course_id, class_name) values ('C0377', 'Advanced Script.NET - Class 1');
insert into classes (course_id, class_name) values ('C0377', 'Advanced Script.NET - Class 2');
insert into classes (course_id, class_name) values ('C0378', 'Practical Script.NET - Class 1');
insert into classes (course_id, class_name) values ('C0378', 'Practical Script.NET - Class 2');
insert into classes (course_id, class_name) values ('C0379', 'Beginner T-SQL - Class 1');
insert into classes (course_id, class_name) values ('C0379', 'Beginner T-SQL - Class 2');
insert into classes (course_id, class_name) values ('C0380', 'Intermediate T-SQL - Class 1');
insert into classes (course_id, class_name) values ('C0380', 'Intermediate T-SQL - Class 2');
insert into classes (course_id, class_name) values ('C0381', 'Advanced T-SQL - Class 1');
insert into classes (course_id, class_name) values ('C0381', 'Advanced T-SQL - Class 2');
insert into classes (course_id, class_name) values ('C0382', 'Practical T-SQL - Class 1');
insert into classes (course_id, class_name) values ('C0382', 'Practical T-SQL - Class 2');
insert into classes (course_id, class_name) values ('C0383', 'Beginner Unix Shell - Class 1');
insert into classes (course_id, class_name) values ('C0383', 'Beginner Unix Shell - Class 2');
insert into classes (course_id, class_name) values ('C0384', 'Intermediate Unix Shell - Class 1');
insert into classes (course_id, class_name) values ('C0384', 'Intermediate Unix Shell - Class 2');
insert into classes (course_id, class_name) values ('C0385', 'Advanced Unix Shell - Class 1');
insert into classes (course_id, class_name) values ('C0385', 'Advanced Unix Shell - Class 2');
insert into classes (course_id, class_name) values ('C0386', 'Practical Unix Shell - Class 1');
insert into classes (course_id, class_name) values ('C0386', 'Practical Unix Shell - Class 2');
insert into classes (course_id, class_name) values ('C0387', 'Beginner Visual Basic .NET - Class 1');
insert into classes (course_id, class_name) values ('C0387', 'Beginner Visual Basic .NET - Class 2');
insert into classes (course_id, class_name) values ('C0388', 'Intermediate Visual Basic .NET - Class 1');
insert into classes (course_id, class_name) values ('C0388', 'Intermediate Visual Basic .NET - Class 2');
insert into classes (course_id, class_name) values ('C0389', 'Advanced Visual Basic .NET - Class 1');
insert into classes (course_id, class_name) values ('C0389', 'Advanced Visual Basic .NET - Class 2');
insert into classes (course_id, class_name) values ('C0390', 'Practical Visual Basic .NET - Class 1');
insert into classes (course_id, class_name) values ('C0390', 'Practical Visual Basic .NET - Class 2');
insert into classes (course_id, class_name) values ('C0391', 'Beginner XML - Class 1');
insert into classes (course_id, class_name) values ('C0391', 'Beginner XML - Class 2');
insert into classes (course_id, class_name) values ('C0392', 'Intermediate XML - Class 1');
insert into classes (course_id, class_name) values ('C0392', 'Intermediate XML - Class 2');
insert into classes (course_id, class_name) values ('C0393', 'Advanced XML - Class 1');
insert into classes (course_id, class_name) values ('C0393', 'Advanced XML - Class 2');
insert into classes (course_id, class_name) values ('C0394', 'Practical XML - Class 1');
insert into classes (course_id, class_name) values ('C0394', 'Practical XML - Class 2');
insert into classes (course_id, class_name) values ('C0395', 'Beginner Vim Script - Class 1');
insert into classes (course_id, class_name) values ('C0395', 'Beginner Vim Script - Class 2');
insert into classes (course_id, class_name) values ('C0396', 'Intermediate Vim Script - Class 1');
insert into classes (course_id, class_name) values ('C0396', 'Intermediate Vim Script - Class 2');
insert into classes (course_id, class_name) values ('C0397', 'Advanced Vim Script - Class 1');
insert into classes (course_id, class_name) values ('C0397', 'Advanced Vim Script - Class 2');
insert into classes (course_id, class_name) values ('C0398', 'Practical Vim Script - Class 1');
insert into classes (course_id, class_name) values ('C0398', 'Practical Vim Script - Class 2');
insert into classes (course_id, class_name) values ('C0399', 'Beginner Wolfram - Class 1');
insert into classes (course_id, class_name) values ('C0399', 'Beginner Wolfram - Class 2');
insert into classes (course_id, class_name) values ('C0400', 'Intermediate Wolfram - Class 1');
insert into classes (course_id, class_name) values ('C0400', 'Intermediate Wolfram - Class 2');
insert into classes (course_id, class_name) values ('C0401', 'Advanced Wolfram - Class 1');
insert into classes (course_id, class_name) values ('C0401', 'Advanced Wolfram - Class 2');
insert into classes (course_id, class_name) values ('C0402', 'Practical Wolfram - Class 1');
insert into classes (course_id, class_name) values ('C0402', 'Practical Wolfram - Class 2');
